### ISSUE TITLE
Use real api  request to replace the mock data, such as Alamofire

### ISSUE THREAD

**Issue by gideonsenku** [PankajGaikar/Instagram-SwiftUI#3]
**Is your feature request related to a problem? Please describe.**
This iOS project is fantastic for someone like me who wants to learn iOS development. In a real app, we need to request some data and process it, unlike this project, which currently doesn't use real data. Could you share u how to send request and how to process the data?

**Describe the solution you'd like**
Add Alamofire to resolve it

**Comment by PankajGaikar** [comment]
Hi @GideonSenku ,
This app is meant to be a SwiftUI demonstration just to render the UI and I never planned to add backend/data fetch logic. I am open to review pull requests, feel free to do that.
Thanks
